#ifndef MONSOON_GRAPHIC_RENDER_BASICDRAW_TARGETS
#define MONSOON_GRAPHIC_RENDER_BASICDRAW_TARGETS

#define MONSOON_TARGET_COUNT 1

enum MONS_BasicDrawRenderTargets
{
  MONS_BASICDRAE_RENDERTARGET_NULL,
  MONS_BASICDRAE_RENDERTARGET_RECTANGLE
};

#endif
