#include "Monsoon/Graphic/API/OpenGL/GL/glcorearb.h"
#include <Monsoon/SystemHeaders.h>
#include <Monsoon/Graphic/API/OpenGL/OpenGL.h>

PFNWGLCREATECONTEXTPROC  MONS_wglCreateContext = NULL;
PFNWGLMAKECURRENTPROC    MONS_wglMakeCurrent = NULL;
PFNWGLDELETECONTEXTPROC  MONS_wglDeleteContext = NULL;
PFNWGLGETPROCADDRESSPROC MONS_wglGetProcAddress = NULL;

PFNWGLCREATECONTEXTATTRIBSARBPROC MONS_wglCreateContextAttribsARB = NULL;
PFNWGLCHOOSEPIXELFORMATARBPROC MONS_wglChoosePixelFormatARB = NULL;
PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = NULL;

PFNGLGETSTRINGPROC MONS_glGetString = NULL;
PFNGLCLEARCOLORPROC MONS_glClearColor = NULL;
PFNGLCLEARPROC MONS_glClear = NULL;

PFNGLCREATESHADERPROC MONS_glCreateShader = NULL;
PFNGLSHADERSOURCEPROC MONS_glShaderSource = NULL;
PFNGLCOMPILESHADERPROC MONS_glCompileShader = NULL;
PFNGLGETSHADERIVPROC MONS_glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC MONS_glGetShaderInfoLog = NULL;
PFNGLGETSHADERINFOLOGPROC  MONS_glGetShaderLog = NULL;
PFNGLCREATEPROGRAMPROC MONS_glCreateProgram = NULL;
PFNGLATTACHSHADERPROC MONS_glAttachShader = NULL;
PFNGLLINKPROGRAMPROC MONS_glLinkProgram = NULL;
PFNGLGETPROGRAMIVPROC MONS_glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC MONS_glGetProgramInfoLog = NULL;
PFNGLGENBUFFERSPROC MONS_glGenBuffers = NULL;
PFNGLBINDBUFFERPROC MONS_glBindBuffer = NULL;
PFNGLGENVERTEXARRAYSPROC MONS_glGenVertexArrays = NULL;
PFNGLBINDVERTEXARRAYPROC MONS_glBindVertexArray = NULL;
PFNGLVERTEXATTRIBPOINTERPROC MONS_glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC MONS_glEnableVertexAttribArray = NULL;
PFNGLBUFFERDATAPROC MONS_glBufferData = NULL;
PFNGLUSEPROGRAMPROC MONS_glUseProgram = NULL;
PFNGLDRAWELEMENTSPROC MONS_glDrawElements = NULL;
PFNGLPOLYGONMODEPROC MONS_glPolygonMode = NULL;
PFNGLGETUNIFORMLOCATIONPROC MONS_glGetUniformLocation = NULL;
PFNGLUNIFORM1FPROC MONS_glUniform1f = NULL;
PFNGLDELETESHADERPROC MONS_glDeleteShader = NULL;
PFNGLDELETEPROGRAMPROC MONS_glDeleteProgram = NULL;
PFNGLGETPROGRAMINTERFACEIVPROC MONS_glGetProgramInterfaceiv = NULL;
PFNGLGETPROGRAMRESOURCEIVPROC MONS_glGetProgramResourceiv = NULL;
PFNGLGETPROGRAMRESOURCENAMEPROC MONS_glGetProgramResourceName = NULL;
PFNGLGETACTIVEUNIFORMPROC MONS_glGetActiveUniform = NULL;
PFNGLUNIFORM3FPROC MONS_glUniform3f = NULL;
PFNGLGETINTEGERVPROC MONS_glGetIntegerv = NULL;
PFNGLUNIFORMMATRIX4FVPROC MONS_glUniformMatrix4fv = NULL;
PFNGLUNIFORM2FPROC MONS_glUniform2f = NULL;
