#include <Monsoon/SystemHeaders.h>
#include <Monsoon/Graphic/API/OpenGL/OpenGL.h>

PFNWGLCREATECONTEXTPROC  MONS_wglCreateContext = NULL;
PFNWGLMAKECURRENTPROC    MONS_wglMakeCurrent = NULL;
PFNWGLDELETECONTEXTPROC  MONS_wglDeleteContext = NULL;
PFNWGLGETPROCADDRESSPROC MONS_wglGetProcAddress = NULL;

PFNWGLCREATECONTEXTATTRIBSARBPROC MONS_wglCreateContextAttribsARB = NULL;
PFNWGLCHOOSEPIXELFORMATARBPROC MONS_wglChoosePixelFormatARB = NULL;
PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = NULL;

PFNGLGETSTRINGPROC MONS_glGetString = NULL;
PFNGLCLEARCOLORPROC MONS_glClearColor = NULL;
PFNGLCLEARPROC MONS_glClear = NULL;
